image: node:latest

variables:
  SONAR_PROJECT_KEY: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME

stages:
  - test
  - analysis

job:
  stage: test
  script: 
    - exit 0

PerformAnalysis:
  image: pervasivetut/sonar-qt-analyzer
  stage: analysis
  tags:
    - nodejs
  script:
    - echo 
    - echo $SONARQUBE_URL $SONARQUBE_TOKEN
    - sonar-scanner -X -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login="pia" -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID

